version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      bash -c "
      cd ssproject/ &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py createsuperuser --username admin --email admin@example.com --noinput &&
      gunicorn ssproject.wsgi:application --bind 0.0.0.0:8000
      "
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15.3
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
volumes:
  postgres_data:

