# Generated by Django 4.0.6 on 2023-12-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='цена продукта')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
