# Generated by Django 4.0.6 on 2023-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Наименование"),
        ),
    ]
