# Generated by Django 4.0.6 on 2023-12-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("paymentapp", "0007_alter_discount_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="orders",
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="paymentapp.discount",
            ),
        ),
    ]
