# Generated by Django 4.0.6 on 2023-12-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("paymentapp", "0010_alter_tax_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tax",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="tax",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxes",
                to="paymentapp.tax",
            ),
        ),
    ]
